### ISSUE TITLE
Error Nodemon and Node 

### ISSUE THREAD

**Issue by wrj95** [wrj95/NodeDock#1]
<p>Hi Guys</p>

<p>When I execute my <b>server.js</b>  in Node Container, appear this error msg:</p>
"
<b>**_events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] _(net.js:1345:14)_
    at listenInCluster (net.js:1386:12)
    at doListen (net.js:1501:7)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
Emitted 'error' event at:
    at emitErrorNT (net.js:1365:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    [... lines matching original stack trace ...]
    at bootstrap_node.js:666:3_** "
</b>

<p>Anyone can help me ?</p>

**Comment by wrj95** [comment]
<p>I got it resolve this problem, it was not a error, I was executing a Code File that already runnig in container</p>
